export const icons = {
  home: require("../../assets/icons/home.png"),
  pin: require("../../assets/icons/pin.png"),
  menu: require("../../assets/icons/menu.png"),
  "Partly cloudy": require("../../assets/icons/weatherIcons/sun/27.png"), 
  "Moderate rain": require("../../assets/icons/weatherIcons/cloud/7.png"), 
  "Patchy rain possible": require("../../assets/icons/weatherIcons/sun/8.png"), 
  "Sunny": require("../../assets/icons/weatherIcons/sun/26.png"),  
  "Clear": require("../../assets/icons/weatherIcons/sun/26.png"),  
  "Overcast": require("../../assets/icons/weatherIcons/cloud/35.png"), 
  "Cloudy": require("../../assets/icons/weatherIcons/cloud/35.png"), 
  "Rain shower": require("../../assets/icons/weatherIcons/cloud/7.png"), 
  "Light rain shower": require("../../assets/icons/weatherIcons/cloud/17.png"), 
  "Torrential rain shower": require("../../assets/icons/weatherIcons/cloud/12.png"),
  "Moderate rain at times": require("../../assets/icons/weatherIcons/cloud/7.png"),  
  "Moderate or heavy freezing rain": require("../../assets/icons/weatherIcons/cloud/22.png"),  
  "Moderate or heavy rain shower": require("../../assets/icons/weatherIcons/sun/8.png"),  
  "Moderate or heavy rain with thunder": require("../../assets/icons/weatherIcons/cloud/17.png"),  
  "Mist": require("../../assets/icons/weatherIcons/sun/4.png"),  
  "other": require("../../assets/icons/weatherIcons/cloud/7.png")  
};
